on:
  push:
    branches:
      - develop
      - master

jobs:
  setup:
    runs-on: docker
    outputs:
      tag: ${{ steps.tag.outputs.name }}
    steps:
      - name: "Retrieve version"
        id: version
        uses: https://forgejo.van-de-weerd.net/parcifal/common/toml-attribute@master
        with:
          key: project.version

      - name: "Determine tag"
        id: tag
        shell: bash
        run: |
          TAG="${{ steps.version.outputs.value }}"
          
          if [ "${{ github.ref_name }}" = "develop" ]; then
            TAG="$TAG-dev"
          fi
          
          echo "$TAG"
          echo "name=$TAG" >> "$GITHUB_OUTPUT"

  build:
    runs-on: docker
    outputs:
      dist: ${{ steps.build.outputs.dist }}
    steps:
      - name: "Build dist"
        id: build
        uses: https://forgejo.van-de-weerd.net/parcifal/common/python/build@master

      - name: "Upload dist"
        uses: https://data.forgejo.org/actions/upload-artifact@v3
        with:
          name: "dist"
          path: |
            ${{ steps.build.outputs.dist }}*.tar.gz
            ${{ steps.build.outputs.dist }}*.whl

  publish:
    runs-on: docker
    needs: build
    steps:
      - name: "Download dist"
        uses: https://data.forgejo.org/actions/download-artifact@v3
        with:
          name: "dist"
          path: |
            ${{ needs.build.outputs.dist }}*.tar.gz
            ${{ needs.build.outputs.dist }}*.whl

      - name: "Publish to PyPI Test"
        if: ${{ github.ref_name == 'develop' }}
        uses: https://forgejo.van-de-weerd.net/parcifal/common/twine@master
        with:
          repository: testpypi
          dist: ${{ needs.build.outputs.dist }}
        env:
          TWINE_USERNAME: ${{ vars.PYPI_TEST_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}

      - name: "Publish to PyPI"
        if: ${{ github.ref_name == 'master' }}
        uses: https://forgejo.van-de-weerd.net/parcifal/common/twine@master
        with:
          repository: pypi
          dist: ${{ needs.build.outputs.dist }}
        env:
          TWINE_USERNAME: ${{ vars.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - name: "Publish to Forgejo PyPI"
        if: ${{ github.ref_name == 'master' }}
        uses: https://forgejo.van-de-weerd.net/parcifal/common/twine@master
        with:
          repository: https://forgejo.van-de-weerd.net/api/packages/parcifal/pypi
          dist: ${{ needs.build.outputs.dist }}
        env:
          TWINE_USERNAME: ${{ vars.FORGEJO_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.FORGEJO_PYPI_TOKEN }}

  release:
      runs-on: docker
      needs:
        - setup
        - build
      steps:
        - name: "Download dist"
          uses: https://data.forgejo.org/actions/download-artifact@v3
          with:
            name: "dist"
            path: ${{ needs.build.outputs.dist }}

        - name: "Tag version"
          uses: https://forgejo.van-de-weerd.net/parcifal/common/tag@master
          with:
            tag: ${{ needs.setup.outputs.tag }}
            message: "Tag version ${{ needs.setup.outputs.tag }}"

        - name: "Set release"
          id: release
          uses: https://forgejo.van-de-weerd.net/parcifal/common/release@master
          with:
            tag: ${{ needs.setup.outputs.tag }}
            attachment: |
              ${{ needs.build.outputs.dist }}*.tar.gz
              ${{ needs.build.outputs.dist }}*.whl
