on:
  push:
    branches:
      - develop
      - master

jobs:
  publish:
    runs-on: docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - uses: https://forgejo.van-de-weerd.net/parcifal/common/python-build@master

      - if: ${{ github.ref_name == 'develop' }}
        uses: https://forgejo.van-de-weerd.net/parcifal/common/twine@master
        with:
          repository: testpypi
        env:
          TWINE_USERNAME: ${{ vars.PYPI_TEST_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_TOKEN }}

      - if: ${{ github.ref_name == 'master' }}
        uses: https://forgejo.van-de-weerd.net/parcifal/common/twine@master
        with:
          repository: pypi
        env:
          TWINE_USERNAME: ${{ vars.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

      - if: ${{ github.ref_name == 'master' }}
        uses: https://forgejo.van-de-weerd.net/parcifal/common/twine@master
        with:
          repository: https://forgejo.van-de-weerd.net/api/packages/parcifal/pypi@master
        env:
          TWINE_USERNAME: ${{ vars.FORGEJO_PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.FORGEJO_PYPI_TOKEN }}

      - id: version
        uses: https://forgejo.van-de-weerd.net/parcifal/common/toml-attribute@master
        with:
          attribute: project.version

      - id: tag
        shell: bash
        run: |
          TAG="${{ steps.version.outputs.value }}"
          
          if [ "${{ github.ref_name }}" = "develop" ]; then
            TAG="$TAG-dev"
          fi
          
          echo "name=$TAG" >> "$GITHUB_STEP_OUTPUT"

      - uses: https://forgejo.van-de-weerd.net/parcifal/common/tag-create@master
        with:
          tag: ${{ steps.tag.name }}
          message: "Tag version ${{ steps.tag.name }}"

      - id: release
        uses: https://forgejo.van-de-weerd.net/parcifal/common/release-create@master
        with:
          tag: ${{ steps.tag.name }}
          attachment: ./dist/*.tar.gz
