on: [ push ]

jobs:
  test:
    runs-on: docker
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v3

      - name: "Run PyTest"
        uses: https://forgejo.van-de-weerd.net/parcifal/common/pytest@master
